<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_enableProfileEdit-enabled</name>
   <tag></tag>
   <elementGuidId>4787d725-5c7e-4ffc-ba84-a64ba4fd3845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='enableProfileEdit-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;enableProfileEdit-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f996751-c470-4cb8-a8ca-13a21d8b27e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f0c45c76-955d-4e23-a76a-b2e799f0de7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enableProfileEdit-enabled</value>
      <webElementGuid>aa925425-1bed-4aec-9ce2-c6710594360c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[4]/label[1]/input[1]</value>
      <webElementGuid>43c1f06d-b0eb-4c7f-b136-6a99d32a79b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='enableProfileEdit-enabled']</value>
      <webElementGuid>5c131af1-a7f0-4c83-981f-fa30bb4cacb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[4]/label/input</value>
      <webElementGuid>e363e7b4-2ab9-47dc-bdc1-5665a12ef9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/input</value>
      <webElementGuid>4f084af6-fd4c-4704-a96e-def8bf5c0b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'enableProfileEdit-enabled']</value>
      <webElementGuid>24763b15-8592-4807-9f57-47cf854d624a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
