<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_groupChannel_input_camera_enablePhoto_ccd320</name>
   <tag></tag>
   <elementGuidId>f518e7b3-57bd-4ade-9622-6d4667116615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannel_input_camera_enablePhoto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannel_input_camera_enablePhoto&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce26482-dcef-4a10-b5b4-f995f129a3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>21fcf0c8-db65-402c-8dae-aca634e6accb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannel_input_camera_enablePhoto</value>
      <webElementGuid>30efdb4d-0a70-4b55-9252-44c18311f93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[15]/label[2]/input[1]</value>
      <webElementGuid>7fd5c3e6-b4ef-4c87-9f47-db6383d531fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannel_input_camera_enablePhoto']</value>
      <webElementGuid>4be83077-48b7-439d-b013-960ab1c884dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[15]/label[2]/input</value>
      <webElementGuid>4301417e-7980-4089-b385-655d118e082d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/label[2]/input</value>
      <webElementGuid>269e9b6f-b9b7-4aaf-867a-476fd0f0d367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannel_input_camera_enablePhoto']</value>
      <webElementGuid>43084ec8-5a6e-4aeb-a494-bd3d082153e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
