<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_groupChannelList_enableTypingI_9a4e86</name>
   <tag></tag>
   <elementGuidId>d7ca7d91-b3bc-4853-aa67-8e56b2f940ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannelList_enableTypingIndicator-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannelList_enableTypingIndicator-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d312750-66ae-467c-9060-02e023f7ecfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c089ced2-93e3-4b53-b48a-318154cb8a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannelList_enableTypingIndicator-enabled</value>
      <webElementGuid>4d6c8122-15fe-4527-8162-4953c843d905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[25]/label[1]/input[1]</value>
      <webElementGuid>6ba9cd8d-588d-43af-9443-7f3e23d93db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannelList_enableTypingIndicator-enabled']</value>
      <webElementGuid>1bd9436d-8425-47a8-8fab-32cdd5c4e4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[25]/label/input</value>
      <webElementGuid>f70af5ea-a75b-440d-b931-9cbf500366ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/label/input</value>
      <webElementGuid>49359812-97c7-47cf-99c8-ff9ffd7dc049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannelList_enableTypingIndicator-enabled']</value>
      <webElementGuid>2c76d465-b89d-4a32-bdef-4d263a1bfb0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
