<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_groupChannel_enableVoiceMessag_5d6052</name>
   <tag></tag>
   <elementGuidId>f8a10afa-3f36-4114-bb84-dca43138ed2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannel_enableVoiceMessage-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannel_enableVoiceMessage-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>103e5ff5-16a3-4900-8620-cb99bf212158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b786b08-f434-45cd-a588-95938ddafeb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannel_enableVoiceMessage-enabled</value>
      <webElementGuid>4712036b-f877-4989-a17c-f9745a2cd8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[14]/label[1]/input[1]</value>
      <webElementGuid>e916b8e3-5daa-41dd-91ab-e3af70d41245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannel_enableVoiceMessage-enabled']</value>
      <webElementGuid>ab51245e-8d6e-4ad3-adc1-3691dd9326bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[14]/label/input</value>
      <webElementGuid>34830ebe-fdf0-48c7-a9a6-a2738a42974c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/label/input</value>
      <webElementGuid>80febf2f-7d49-4a4e-99c6-d8283cdcfbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannel_enableVoiceMessage-enabled']</value>
      <webElementGuid>007c1a47-9e3d-42cc-8e3f-3fbf6bdb1304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
