<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_enableProfileEdit_enableProfileEdit</name>
   <tag></tag>
   <elementGuidId>03f16af3-beaa-4182-993c-c3e83eb7a13d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='enableProfileEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;enableProfileEdit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d14933d-3387-4e0e-bb5a-bdc1c60a3054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6e36b335-dc80-4f38-bc30-76758e9a8335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enableProfileEdit</value>
      <webElementGuid>77c7cb15-e9cd-4d4b-a650-3c908765d174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[4]/label[2]/input[1]</value>
      <webElementGuid>c156ec46-57ba-4322-9736-42690532f08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='enableProfileEdit']</value>
      <webElementGuid>92ee45b8-af3e-4250-8fe2-8dc2849756e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[4]/label[2]/input</value>
      <webElementGuid>5ac9af95-beda-47d9-a662-a76c54250378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>368b5708-ea1b-4f36-90bd-bd3059eca8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'enableProfileEdit']</value>
      <webElementGuid>e5f4d4dd-2c0b-4e9f-a4ac-3250e0c67c37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
