<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_groupChannel_input_camera_enableVideo_23f2d2</name>
   <tag></tag>
   <elementGuidId>1f6623b1-42a2-4072-8102-4682d895968a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannel_input_camera_enableVideo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannel_input_camera_enableVideo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5660597-0663-4c25-b432-657e6f5a503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>88cb4a12-c1dc-4bff-b5dd-e005611a914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannel_input_camera_enableVideo</value>
      <webElementGuid>9288dfbd-870a-4de9-a0de-c2ea46751bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[16]/label[2]/input[1]</value>
      <webElementGuid>e2a9fe01-0bc1-40e2-826f-db66d4b79eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannel_input_camera_enableVideo']</value>
      <webElementGuid>30b91a82-1931-418a-911c-8ba570ea0f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[16]/label[2]/input</value>
      <webElementGuid>bb16eb28-5400-4217-a1a1-192f6e8260ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/label[2]/input</value>
      <webElementGuid>df83be22-e55f-4376-92fa-d2fed3e9136a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannel_input_camera_enableVideo']</value>
      <webElementGuid>9800e658-6efb-4a58-af97-3fffe510cad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
