<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_common_enableUsingDefaultUserProfile__0c5541</name>
   <tag></tag>
   <elementGuidId>48150a3b-1b59-45d7-98af-931756a5b264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='common_enableUsingDefaultUserProfile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;common_enableUsingDefaultUserProfile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19325a16-be20-460f-866d-4f1a1141903b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fe78febc-2c75-424e-a9a9-d0a7ac73acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>common_enableUsingDefaultUserProfile</value>
      <webElementGuid>70e25c87-c4c3-464d-b38e-7ee2e2b127ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[6]/label[2]/input[1]</value>
      <webElementGuid>09398162-580e-4e3f-a571-916e27631c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='common_enableUsingDefaultUserProfile']</value>
      <webElementGuid>29906a6d-d755-488c-b218-88dea5e3b841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[6]/label[2]/input</value>
      <webElementGuid>88521111-ea5c-46f8-9f48-dcfcbc978b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label[2]/input</value>
      <webElementGuid>df20d5f6-10ea-4c4e-bd1d-e6f389589c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'common_enableUsingDefaultUserProfile']</value>
      <webElementGuid>d8981e01-dd20-40c3-8d4a-136607eccede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
