<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_groupChannel_enableOgtag_groupChannel_6386a3</name>
   <tag></tag>
   <elementGuidId>6fd0fdcf-c92a-4271-bc20-7c8041606291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannel_enableOgtag']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannel_enableOgtag&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>339411d3-3bf3-41d0-8ae2-5cdb591dadd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ac33365-967f-436b-b653-c789b1cf1f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannel_enableOgtag</value>
      <webElementGuid>404dc5a2-8a1f-4089-a6c5-107820d6901c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[7]/label[2]/input[1]</value>
      <webElementGuid>15ca6dae-1a43-4b92-9c91-48d4c40425d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannel_enableOgtag']</value>
      <webElementGuid>0fdebddf-9f1a-47e5-9cfb-b9ffcc3835ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[7]/label[2]/input</value>
      <webElementGuid>05d48d2e-ab6c-44ac-b775-1be4fa3d356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label[2]/input</value>
      <webElementGuid>a428753f-7663-4516-9df3-dd651ebcc719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannel_enableOgtag']</value>
      <webElementGuid>546a5523-e394-4960-8e3e-bd75df4014fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
