<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_groupChannel_enableReactions_groupCha_0e1357</name>
   <tag></tag>
   <elementGuidId>17e43526-51f3-4fc2-8429-a5a1e515c683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannel_enableReactions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannel_enableReactions&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f08e5c5-c14d-4094-ac51-9c075cdfecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>be548633-2365-4ea5-96bc-2de29318a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannel_enableReactions</value>
      <webElementGuid>2ff3689c-0c92-478c-9224-d1b3762af163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[9]/label[2]/input[1]</value>
      <webElementGuid>a0b9096b-a464-4c50-bbb0-d93fb33b9fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannel_enableReactions']</value>
      <webElementGuid>73cbc8a1-d5ba-4136-86a8-72bcc68c086f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[9]/label[2]/input</value>
      <webElementGuid>c4fff201-a728-4506-b443-1e2f17542609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/label[2]/input</value>
      <webElementGuid>2636f7e1-34b3-4b38-932e-51a85c0e4d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannel_enableReactions']</value>
      <webElementGuid>7ef9e1e7-87d7-45a1-90cc-77f2506f3c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
