<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_enableMultipleFilesMessage-enabled</name>
   <tag></tag>
   <elementGuidId>8a4aa94e-2b6e-41fe-9163-3c418cec731a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='enableMultipleFilesMessage-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;enableMultipleFilesMessage-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98cf1700-e013-4651-b498-5f2f9a9b2f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>318154a5-3f51-4627-9225-4ee78f3203e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enableMultipleFilesMessage-enabled</value>
      <webElementGuid>4455d916-d692-4d2b-9f65-fe774788abec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[5]/label[1]/input[1]</value>
      <webElementGuid>b3d9f330-004c-4b7f-a027-e99c1dcd0dc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='enableMultipleFilesMessage-enabled']</value>
      <webElementGuid>af8970f2-e4ee-4b88-98e5-972da3130bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[5]/label/input</value>
      <webElementGuid>d42918ad-8189-4db8-8c3a-e7ebae93523f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/input</value>
      <webElementGuid>82a72038-2735-4248-b8c1-9ab349a38f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'enableMultipleFilesMessage-enabled']</value>
      <webElementGuid>373722e0-0ace-4518-8846-65424eb6cd1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
