<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_common_enableUsingDefaultUserP_120c0a</name>
   <tag></tag>
   <elementGuidId>ceba1c49-b22e-4846-bdaf-a42710545552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='common_enableUsingDefaultUserProfile-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;common_enableUsingDefaultUserProfile-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57d0a034-5aca-4c18-9612-d83721e4519c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c4718c0f-a8ef-4d11-a1a2-7a29e6d51f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>common_enableUsingDefaultUserProfile-enabled</value>
      <webElementGuid>31e889b2-f669-419f-8007-0f049f3a203e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[6]/label[1]/input[1]</value>
      <webElementGuid>4dac0ca1-f273-4ef8-80df-0792470fc53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='common_enableUsingDefaultUserProfile-enabled']</value>
      <webElementGuid>77bc20e3-e499-4d43-8bdc-47579868de60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[6]/label/input</value>
      <webElementGuid>4191e6e6-4557-4fbd-a2a2-072b03a09d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label/input</value>
      <webElementGuid>dba42c5a-d486-490c-a7c2-18fd11778cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'common_enableUsingDefaultUserProfile-enabled']</value>
      <webElementGuid>66c5ea09-5cbc-4a6c-a332-843631ea2b6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
