<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_groupChannelList_enableTypingIndicato_defe84</name>
   <tag></tag>
   <elementGuidId>555531f3-81ba-4d10-b59e-8d78e6b72744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannelList_enableTypingIndicator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannelList_enableTypingIndicator&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a272cb8-4eae-42bb-8f3c-5d176812edb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2c064aad-1dd2-4b97-9caa-b628ee8e75fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannelList_enableTypingIndicator</value>
      <webElementGuid>5de08b02-cfeb-4442-b7bc-ce1fcda6549a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[25]/label[2]/input[1]</value>
      <webElementGuid>a79e4122-54a1-46be-b2b1-f891c5ebc407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannelList_enableTypingIndicator']</value>
      <webElementGuid>ba81bd49-4095-4f03-a92f-217a38047adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[25]/label[2]/input</value>
      <webElementGuid>c81f6ae3-0ba7-4187-9c27-a0a30213f84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/label[2]/input</value>
      <webElementGuid>004641d6-4838-44ff-aa28-c0aec800a9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannelList_enableTypingIndicator']</value>
      <webElementGuid>f123e0d5-bcc4-4738-bddc-64902d7569df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
