<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_groupChannelList_enableMessage_10a4dd</name>
   <tag></tag>
   <elementGuidId>5ba35356-1a75-4246-9556-abfbac34aaa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannelList_enableMessageReceiptStatus-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannelList_enableMessageReceiptStatus-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3efa8e68-6c27-47e9-b519-376d84fb9858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>87f111c8-aa80-422a-9c09-c80dca5659dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannelList_enableMessageReceiptStatus-enabled</value>
      <webElementGuid>920119c6-de8b-461d-8921-b60f92c752eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[26]/label[1]/input[1]</value>
      <webElementGuid>ac946e89-348f-4e71-81ed-57696bebe94c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannelList_enableMessageReceiptStatus-enabled']</value>
      <webElementGuid>f52ae125-f5bf-4548-b5c0-dc22ca5627c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[26]/label/input</value>
      <webElementGuid>ddca09f1-1527-4022-a8e8-64921e107169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/label/input</value>
      <webElementGuid>f8e746f4-7613-49ca-ad2c-af344c8ff0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannelList_enableMessageReceiptStatus-enabled']</value>
      <webElementGuid>fc82cd12-2eb3-47f3-96a7-13191682dbc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
