<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_groupChannel_enableSuggestedRe_06cf33</name>
   <tag></tag>
   <elementGuidId>1ad46ca4-032e-46d9-bc8e-ed01f3d99ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannel_enableSuggestedReplies-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannel_enableSuggestedReplies-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09866dfc-7486-490d-878c-717d057e7f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>481b37ab-ff25-49c8-931f-4eabec246081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannel_enableSuggestedReplies-enabled</value>
      <webElementGuid>217dbcfe-e84a-407c-b67f-990735497a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[22]/label[1]/input[1]</value>
      <webElementGuid>9673f172-76b1-4426-b5b0-2f588f4f8725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannel_enableSuggestedReplies-enabled']</value>
      <webElementGuid>4fa6da48-2e05-4e66-a245-9bd4d7eddb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[22]/label/input</value>
      <webElementGuid>aff4274a-a549-4af6-997e-ddd823d644db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/label/input</value>
      <webElementGuid>2fec9ff6-27c5-4be7-923e-a188ae340de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannel_enableSuggestedReplies-enabled']</value>
      <webElementGuid>c410307d-53d8-4899-839b-a249bec9730e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
