<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_openChannel_enableOgtag-enabled</name>
   <tag></tag>
   <elementGuidId>0787dd2c-4533-4b03-9c3a-5b03a405fac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='openChannel_enableOgtag-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;openChannel_enableOgtag-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88ff46a3-d614-400a-a8cc-dada94189a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b8cbc667-ed95-41d6-8b59-2a0e73708d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>openChannel_enableOgtag-enabled</value>
      <webElementGuid>82aed25d-e544-4e66-b2fa-139282d899ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[28]/label[1]/input[1]</value>
      <webElementGuid>9d8aa841-acea-431c-a0ee-6eaa0b65325b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='openChannel_enableOgtag-enabled']</value>
      <webElementGuid>4f711435-0bd3-4e30-b484-30f8313042c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[28]/label/input</value>
      <webElementGuid>25539196-275e-4730-80b8-e86dbbf1e96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/label/input</value>
      <webElementGuid>f633ba32-f20f-4f23-82b2-80f591bceb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'openChannel_enableOgtag-enabled']</value>
      <webElementGuid>627fb671-e597-49fd-a21c-9ad5cffd3513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
