<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable_groupChannelSettings_enableMes_c6099d</name>
   <tag></tag>
   <elementGuidId>de2a7c17-2125-49eb-b166-a4c507b12852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannelSettings_enableMessageSearch-enabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannelSettings_enableMessageSearch-enabled&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b20e708d-3747-4621-8f35-423e0db43ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b5a025f6-45f3-4bc8-9c74-92ef4043c7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannelSettings_enableMessageSearch-enabled</value>
      <webElementGuid>0547a6ae-f615-4e6f-be49-e7072e74295d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[27]/label[1]/input[1]</value>
      <webElementGuid>9099c2be-695f-4f40-ad0b-a3caf4abab79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannelSettings_enableMessageSearch-enabled']</value>
      <webElementGuid>65105ad7-0763-4b3e-abfc-a5471e764d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[27]/label/input</value>
      <webElementGuid>81f59414-443b-4960-9c60-6403a3818bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/label/input</value>
      <webElementGuid>c2b38117-37a1-4df0-809a-1bf0d0afffaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannelSettings_enableMessageSearch-enabled']</value>
      <webElementGuid>9385daa3-72c9-40a1-b029-0f0235987180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
