<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_enableMultipleFilesMessage_enableMult_185100</name>
   <tag></tag>
   <elementGuidId>9037f60d-a3e2-4d44-a46d-14afba14ce10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='enableMultipleFilesMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;enableMultipleFilesMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0637fd6-9441-4f80-8546-2d05f7a282bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1806aee5-919c-49fc-9e80-f2c7897457f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enableMultipleFilesMessage</value>
      <webElementGuid>28a4ec84-165d-4fd1-ab3a-320d06b67b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[5]/label[2]/input[1]</value>
      <webElementGuid>b3738e96-24c4-486e-b9be-d089ee0fdcc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='enableMultipleFilesMessage']</value>
      <webElementGuid>e6d389ed-5275-43aa-beb9-9b23fcc10352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[5]/label[2]/input</value>
      <webElementGuid>0b45816c-d906-4f03-bc7b-ea2601a4919d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label[2]/input</value>
      <webElementGuid>cc02d819-29ae-495b-b091-36c3c58e3199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'enableMultipleFilesMessage']</value>
      <webElementGuid>03de7ab8-d6fb-4702-80f0-964239599880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
