<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_groupChannelList_enableMessageReceipt_508928</name>
   <tag></tag>
   <elementGuidId>ce1b4326-08fd-4305-b3c2-728d00668b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='groupChannelList_enableMessageReceiptStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;groupChannelList_enableMessageReceiptStatus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d901be43-fe57-439b-ac9a-21f0b1aa14f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2d58a243-f198-4aef-821a-16c6c2a42965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupChannelList_enableMessageReceiptStatus</value>
      <webElementGuid>42d8ae5e-ed7f-4e56-a7a1-43d93c194f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[26]/label[2]/input[1]</value>
      <webElementGuid>172fcf29-efa7-4b3d-8d2d-8d1f1ee41b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='groupChannelList_enableMessageReceiptStatus']</value>
      <webElementGuid>463f453d-38ae-4dd9-91aa-e7eb9dbd58d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[26]/label[2]/input</value>
      <webElementGuid>85e37869-8e53-497f-bbe0-1055b99f2566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/label[2]/input</value>
      <webElementGuid>19dafd08-ca57-404c-ae90-f3d0d1ac885c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'groupChannelList_enableMessageReceiptStatus']</value>
      <webElementGuid>42e141f4-6e67-48a5-808b-d72a7361b4bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
