<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_groupChannel_input_enableDocument</name>
   <tag></tag>
   <elementGuidId>c01dd5e6-825e-4e7b-af12-57cd8315d60f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='builder']/div[19]/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(19) > label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1e4f5410-9f4b-479d-a5a6-6c6868869745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>groupChannel_input_enableDocument</value>
      <webElementGuid>9d4c6434-8cea-4cc8-8f97-0c70810520c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[19]/label[2]</value>
      <webElementGuid>08c24207-f8e1-4686-a19d-3aa0b6ecc00b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[19]/label[2]</value>
      <webElementGuid>a8b6bfcc-348b-4f26-b6b7-b6d7637a0bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[16]/following::label[1]</value>
      <webElementGuid>609c5324-f383-4b84-b5cd-d10da1de2272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='groupChannel_input_gallery_enableVideo'])[1]/following::label[2]</value>
      <webElementGuid>c289cfe2-8735-4f18-b706-ada068209446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[17]/preceding::label[1]</value>
      <webElementGuid>cd80aaa6-6b9c-486d-a9fb-571faa2e3693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/label[2]</value>
      <webElementGuid>60fbeac6-6cbe-4804-89d9-f697cb3da975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'groupChannel_input_enableDocument' or . = 'groupChannel_input_enableDocument')]</value>
      <webElementGuid>747f5e50-93f2-4512-936f-1137ad3f1d70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
