<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Enable</name>
   <tag></tag>
   <elementGuidId>a0f48322-5ce0-46fa-9ad2-ca1d028c3253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='builder']/div[10]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(10) > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f4e0fa2b-07b7-4fca-b1b7-2a7f4dc50ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enable</value>
      <webElementGuid>a5b16822-b9b8-4d1d-9fa5-04b3a7d122ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[10]/label[1]</value>
      <webElementGuid>933aea3c-a741-4264-a2ec-1ec3aaa794cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[10]/label</value>
      <webElementGuid>abb5b4df-c247-4124-8263-bcca99c24b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='groupChannel_enableReactions'])[1]/following::label[1]</value>
      <webElementGuid>5e8a5eb9-3b99-486c-9a0d-b6dd258c92f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[6]/following::label[2]</value>
      <webElementGuid>061f5fa3-1890-4d76-8710-58f59d1296ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='groupChannel_enableReactionsSupergroup'])[1]/preceding::label[1]</value>
      <webElementGuid>299b83b8-7cf9-4ddd-8ac3-b886df52b729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/label</value>
      <webElementGuid>4b1651e2-47ee-4f59-a23f-a824b19d876f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Enable' or . = 'Enable')]</value>
      <webElementGuid>0c0891ce-ea11-4ae6-8f45-2756a934842a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
