<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_groupChannel_input_gallery_enableVideo</name>
   <tag></tag>
   <elementGuidId>1ad76454-4491-4058-836c-fd9050eaf6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='builder']/div[18]/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(18) > label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f31015d4-d8a8-46c6-8dcf-8df4d61a5b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>groupChannel_input_gallery_enableVideo</value>
      <webElementGuid>9021ff7d-a7c1-4423-bc63-33a8a3ef4b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;builder&quot;)/div[18]/label[2]</value>
      <webElementGuid>544094e6-4ffd-4e5e-bb37-67d25fdf76c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='builder']/div[18]/label[2]</value>
      <webElementGuid>0d0a192f-b365-41fc-bd66-44f832201b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[15]/following::label[1]</value>
      <webElementGuid>9f729236-27e0-4bf1-a9fc-b28dd62b8433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='groupChannel_input_gallery_enablePhoto'])[1]/following::label[2]</value>
      <webElementGuid>4ff9bfdf-8c16-420b-9d93-9755cb21ab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[16]/preceding::label[1]</value>
      <webElementGuid>4bef362b-5d87-49ea-9902-d60ed2ad42c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/label[2]</value>
      <webElementGuid>f7d16100-40b6-4be3-abf3-82abe1c418ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'groupChannel_input_gallery_enableVideo' or . = 'groupChannel_input_gallery_enableVideo')]</value>
      <webElementGuid>94a571a0-f8b6-42a9-a3ae-e5ae2f2cd0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
