<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Group</name>
   <tag></tag>
   <elementGuidId>3cfd32c5-7ad3-49a8-bd74-4146cd84d4b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sendbird-modal-root']/div/div/div[2]/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sendbird-add-channel__rectangle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15f77891-53f9-4574-ac23-5281fac13c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-add-channel__rectangle</value>
      <webElementGuid>ce35ef76-1cc4-491d-8e46-ad1d5e4ffc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>467002ed-a576-4b83-8b40-f86d2ce44025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>378e4da8-b767-4cc5-8ce9-45f620eb8847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>2265706a-73cd-4812-a621-059f63f175e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendbird-modal-root&quot;)/div[@class=&quot;sendbird-modal sendbird-add-channel__modal&quot;]/div[@class=&quot;sendbird-modal__content&quot;]/div[@class=&quot;sendbird-modal__body&quot;]/span[@class=&quot;sendbird-label sendbird-label--subtitle-1 sendbird-label--color-onbackground-2&quot;]/div[@class=&quot;sendbird-add-channel__rectangle-wrap&quot;]/div[@class=&quot;sendbird-add-channel__rectangle&quot;]</value>
      <webElementGuid>f32a3557-09f8-41e4-b6ef-c13ad1adf3a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sendbird-modal-root']/div/div/div[2]/span/div/div</value>
      <webElementGuid>e11b748c-6fc3-415b-9d1c-dc28d0d9df85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New channel'])[1]/following::div[5]</value>
      <webElementGuid>601e326d-4c6b-4f7e-b9e0-64aa37f8da48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No channels'])[2]/following::div[10]</value>
      <webElementGuid>3f39a685-cdd5-4a6a-9cf1-e275c9c8244f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>274ab039-b2fd-459f-9790-87912734128d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>e89828a2-fcc5-4f25-ab1e-c3c5500c3683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
